version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            . ./bin/activate-hermit
            hermit install
            go install github.com/jstemmer/go-junit-report@latest
            mkdir ~/report
          when: always
      - run:
          name: Test
          command: |
            . ./bin/activate-hermit
            (go test -v ./... && (cd ./_examples && go test ./...)) 2>&1 | tee report.txt && go-junit-report < report.txt > ~/report/junit.xml
      - run:
          name: Lint
          command: |
            . ./bin/activate-hermit
            go build ./...
            golangci-lint run
      - store_test_results:
          path: ~/report
